# Jekyll setting
timezone: Asia/Tokyo
remote_theme: pages-themes/tactile@v0.2.0
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-linkpreview
  - jekyll-remote-theme
  - rouge
highlighter: rouge
exclude:
  - vendor
excerpt_separator: <!-- more -->
paginate: 10
paginate_path: "/page/:num"

# title
title: ysk24ok.github.io
description: My blog posts, slides and past works
url: https://ysk24ok.github.io
github_url: https://github.com/ysk24ok

# Path
asset_path: /assets
