# jekyll setting
# https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-gist
  - jekyll-paginate
  - rouge
highlighter: rouge
exclude:
  - vendor
excerpt_separator: <!-- more -->
paginate: 10
paginate_path: "/page/:num"

# title
name: ysk24ok.github.io
description: My blog posts, slides and past works
url: //ysk24ok.github.io
github_url: https://github.com/ysk24ok

# Path
asset_path: /assets
reveal_js_path: /lib/reveal.js
