# Jekyll setting
timezone: Asia/Tokyo
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-linkpreview
  - rouge
highlighter: rouge
exclude:
  - vendor
show_excerpts: true
excerpt_separator: <!-- more -->
paginate: 10
paginate_path: "/page/:num"

# Site setting
title: ysk24ok.github.io
author: Yusuke Nishioka
description: ysk24ok's blog posts
twitter_username: ysk24ok
github_username: ysk24ok
